export const TERMS_OF_SERVICE = `
Terms of Service for the 100% Free English Level Test (A1-C2)
Last Updated: May 3rd, 2024

1. Acceptance of Terms
By accessing or using the 100% Free English Level Test (A1-C2) web application (the “Assessment”), you agree to be bound by these Terms of Service. If you do not accept these terms, you must not use the Assessment. Use, completion, or submission of the Assessment constitutes acceptance of these Terms of Service.

2. Nature of the Assessment
The Assessment is an independently created, web-based educational tool presented through a web application. It is provided for informational and educational purposes only and is not a formal examination, certification, or accredited proficiency test.

3. CEFR Disclaimer
The Assessment is independently created and is not affiliated with, endorsed by, authorized by, or certified by the Common European Framework of Reference for Languages (CEFR) or any related governing body. Any CEFR level displayed at the end of the Assessment, including A1, A2, B1, B2, Upper B2-Lower C1, C1, or C2, is only an estimate generated by an internal scoring method. Such result should not be treated as an official certification or as a guaranteed prediction of performance on any CEFR-aligned exam.

4. Licensing and Redistribution
The web application is distributed under the MIT License. Redistribution is permitted provided that appropriate credit is given to the original work in a prominent location of the project.

5. Use Restrictions
The Assessment is provided for personal, non-commercial use only. User conduct must not:
- Use the Assessment for any unlawful, fraudulent, or harmful purpose;
- Attempt to interfere with, bypass, or manipulate the scoring system or test mechanics;
- Copy, reproduce, distribute, or sell Assessment materials without complying with the MIT License terms.
- Copy, reproduce, distribute, or sell Assessment materials without providing proper credit to the original work.

6. Disclaimer of Warranties
The Assessment is provided on an “as is” and “as available” basis. No warranty and no giarntees is made that the Assessment will be uninterrupted, error-free, secure, or suitable for any particular purpose. Any result produced by the Assessment is an estimate only.

7. Limitation of Liability
To the maximum extent permitted by law, no liability is accepted for any loss, damage, decision, or consequence arising from the use of the Assessment or reliance on any result, score, or level displayed.

8. Changes to Terms
These Terms of Service may be updated at any time. Continued use of the Assessment after any update becomes effective constitutes acceptance of the revised terms.
`.trim();

export const PRIVACY_POLICY = `
Privacy Policy for the 100% Free English Level Test (A1-C2)
Last Updated: May 3rd, 2024

1. Scope
This Privacy Policy explains how information is collected, used, disclosed, and transferred when the Assessment is accessed or used. By using the Assessment, you acknowledge the practices described in this Policy. Technical data collection begins automatically through Vercel Analytics as soon as the web application loads.

2. Information Collected via Vercel Analytics
When the web application loads, technical and performance information is collected automatically through Vercel Analytics, including, but not limited to:
- Achieved level or test outcome;
- Country, state, region, territory, city, or other general location derived from IP address;
- Device type, browser type, and operating system;
- Usage, diagnostic, and performance metrics related to interaction with the web application.

3. Third-Party Processing
Information is processed by Vercel Analytics and Vercel infrastructure services for the purposes described in this Policy. Vercel may process this information under its own privacy practices and applicable agreements.

4. Data Sharing and Commercial Use
Personal information may be shared, disclosed, sold, or otherwise processed in accordance with this policy and applicable law. Aggregated, anonymized, or de-identified information may be used or disclosed for analytics, research, reporting, commercial, and other legitimate business purposes.

5. Data Retention and Security
Information is retained for as long as necessary to fulfill the purposes described in this Policy, unless a longer retention period is required by law.

6. Legal Basis and Consent
Processing relies on consent, legitimate interests, or legal obligations where required. By using the Assessment, the user acknowledges and consents to the collection, use, and transfer of information as described to the extent permitted by law.

7. Changes to This Policy
This Privacy Policy may be revised at any time. Continued use of the Assessment after any update becomes effective constitutes acceptance of the revised policy.
`.trim();
